name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm build
      - run: pnpm exec biome ci
      - run: tsc
      - run: pnpm attw

  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm vitest --coverage
      - uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          comment-on: "pr"
